### ISSUE TITLE
docker service does not start, lerna missing?

### ISSUE THREAD

**Issue by rafaelkallis** [hashgraph/hedera-json-rpc-relay#181]
### Description

Hi @Nana-EC 

There seems to be an issue when I try to run the relay node as a docker service. I hope the issue is obvious once you see the logs :) Perhaps the issue is resolved once you have `lerna` as a `dependency` instead of a `devDependency`.

```sh
$ docker-compose up
relay_1  | 
relay_1  | > start
relay_1  | > npx lerna exec --scope @hashgraph/json-rpc-server -- npm run start
relay_1  | 
Need to install the following packages:
relay_1  |   lerna
```

### Steps to reproduce

1. run docker-compose up with the given docker compose file

### Additional context

docker-compose.yaml
```yaml
version: "3.8"

services:
  relay:
    image: "ghcr.io/hashgraph/hedera-json-rpc-relay:0.1.0-rc3"
    ports:
      - 7546:7546
    tty: true
    volumes:
      - ./deploy/config/hedera-relay-local/.env:/home/node/app/.env
```

### Hedera network

testnet

### Version

v0.1.0-rc3

### Operating system

Linux
